name: Daily Current Scraper
on:
  schedule:
    # 8:15 AM IST is 2:45 AM UTC (previous day)
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Environment Variables
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        echo "Bot Token length: ${#BOT_TOKEN}"
        echo "Mongo URI length: ${#MONGO_URI}"
        
        # Debugging - ensure BOT_TOKEN is available (NOTE: Do NOT print the actual token in production logs)
        if [ -z "$BOT_TOKEN" ]; then
          echo "BOT_TOKEN is not set!"
        else
          echo "BOT_TOKEN is set correctly."
        fi
        
        # Debugging - Check if MONGO_URI is available
        if [ -z "$MONGO_URI" ]; then
          echo "MONGO_URI is not set!"
        else
          echo "MONGO_URI is set correctly."
        fi

    - name: Run Scraper
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        # Debug: Ensure BOT_TOKEN and MONGO_URI are passed correctly
        echo "BOT_TOKEN: $BOT_TOKEN"  # Debugging (avoid in production)
        echo "MONGO_URI: $MONGO_URI"  # Debugging (avoid in production)
        
        # Run the scraper script
        python main.py
