name: Daily Current Affairs Scraper
on:
  schedule:
    # 8:15 AM IST is 2:45 AM UTC (previous day)
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Environment Variables
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        echo "Bot Token length: ${#BOT_TOKEN}"
        echo "Mongo URI length: ${#MONGO_URI}"
        # Debug print to confirm the values are set (ensure you're not revealing sensitive data)
        echo "BOT_TOKEN: $BOT_TOKEN"  # This will print the actual token in logs (avoid printing in production)
        echo "MONGO_URI: $MONGO_URI"  # This will print the Mongo URI in logs (avoid printing in production)

    - name: Run Scraper
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        # Debug: Ensure BOT_TOKEN and MONGO_URI are passed correctly
        echo "BOT_TOKEN: $BOT_TOKEN"  # Print token for verification (ensure this is not printed in production)
        echo "MONGO_URI: $MONGO_URI"  # Print Mongo URI for verification (ensure this is not printed in production)
        python main.py
