name: Daily Current Affairs Scraper

on:
  schedule:
    # 8:15 AM IST is 2:45 AM UTC (previous day)
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure MongoDB Connection
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        echo "Configuring MongoDB connection"
    
    - name: Run Scraper
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python main.py
