name: Daily Current Scraper

on:
  schedule:
    # 8:15 AM IST is 2:45 AM UTC (previous day)
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Environment Variables
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        ACESS_TOKEN: ${{ secrets.ACESS_TOKEN }}
        PAGE_ID: ${{ secrets.PAGE_ID }}
      run: |
        echo "Bot Token length: ${#BOT_TOKEN}"
        echo "Mongo URI length: ${#MONGO_URI}"
        echo "App ID length: ${#APP_ID}"
        echo "App Secret length: ${#APP_SECRET}"
        echo "Access Token length: ${#ACESS_TOKEN}"
        echo "Page ID length: ${#PAGE_ID}"
        
        # Debugging - Check if variables are available
        if [ -z "$BOT_TOKEN" ]; then
          echo "BOT_TOKEN is not set!"
        else
          echo "BOT_TOKEN is set correctly."
        fi

        if [ -z "$MONGO_URI" ]; then
          echo "MONGO_URI is not set!"
        else
          echo "MONGO_URI is set correctly."
        fi

        if [ -z "$APP_ID" ]; then
          echo "APP_ID is not set!"
        else
          echo "APP_ID is set correctly."
        fi

        if [ -z "$APP_SECRET" ]; then
          echo "APP_SECRET is not set!"
        else
          echo "APP_SECRET is set correctly."
        fi

        if [ -z "$ACESS_TOKEN" ]; then
          echo "ACESS_TOKEN is not set!"
        else
          echo "ACESS_TOKEN is set correctly."
        fi

        if [ -z "$PAGE_ID" ]; then
          echo "PAGE_ID is not set!"
        else
          echo "PAGE_ID is set correctly."
        fi

    - name: Run Scraper
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        ACESS_TOKEN: ${{ secrets.ACESS_TOKEN }}
        PAGE_ID: ${{ secrets.PAGE_ID }}
      run: |
        # Run the scraper script
        python main.py
